In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plot

In [2]:
# define cols to load
desired_cols = ['DateOfCall','TimeOfCall','IncidentGroup','StopCodeDescription', 'PropertyCategory', 
                'PropertyType', 'Notional Cost (£)', 'NumCalls']

# load dataset
# manually checked: there are no NaN DateOfCall
ds = pd.read_csv('data/lfb_incident.csv', usecols = desired_cols)
ds

,DateOfCall,TimeOfCall,IncidentGroup,StopCodeDescription,PropertyCategory,PropertyType,Notional Cost (£),NumCalls
0,01 Jan 2009,00:00:37,Special Service,Special Service,Road Vehicle,Car,255.0,1.0
1,01 Jan 2009,00:00:46,Special Service,Special Service,Outdoor,Lake/pond/reservoir,NaN,1.0
2,01 Jan 2009,00:03:00,Fire,Secondary Fire,Outdoor,Road surface/pavement,255.0,2.0
3,01 Jan 2009,00:04:27,Fire,Secondary Fire,Outdoor,Domestic garden (vegetation not equipment),255.0,2.0
4,01 Jan 2009,00:05:39,Fire,Secondary Fire,Outdoor,Cycle path/public footpath/bridleway,255.0,1.0
...,...,...,...,...,...,...,...,...
1465055,30 Jun 2022,23:42:53,False Alarm,AFA,Non Residential,Warehouse,364.0,2.0
1465056,30 Jun 2022,23:46:26,Special Service,Special Service,Dwelling,Purpose Built Flats/Maisonettes - Up to 3 stor...,364.0,2.0
1465057,30 Jun 2022,23:46:44,False Alarm,AFA,Non Residential,Pub/wine bar/bar,364.0,1.0
1465058,30 Jun 2022,23:47:55,False Alarm,False alarm - Good intent,Dwelling,Purpose Built Flats/Maisonettes - 4 to 9 storeys,364.0,1.0
1465059,30 Jun 2022,23:48:37,Special Service,Special Service,Dwelling,Purpose Built Flats/Maisonettes - 4 to 9 storeys,364.0,2.0

In [5]:
for col_name in desired_cols:
    print(ds[col_name].value_counts())
    print("=========================")

12 Jul 2021    1058
25 Jul 2021    1043
23 Jun 2016     998
18 Feb 2022     860
03 Mar 2018     835
               ...
12 Jun 2014      99
09 Dec 2014      96
02 Nov 2014      67
01 Nov 2014      48
03 Nov 2014      40
Name: DateOfCall, Length: 4929, dtype: int64
=========================
19:11:16    48
18:02:06    44
18:53:39    44
17:12:19    44
18:12:47    43
            ..
03:32:46     1
05:51:53     1
05:17:30     1
05:13:29     1
03:40:22     1
Name: TimeOfCall, Length: 86385, dtype: int64
=========================
False Alarm        719775
Special Service    459264
Fire               286021
Name: IncidentGroup, dtype: int64
=========================
AFA                                      538675
Special Service                          456160
False alarm - Good intent                160585
Primary Fire                             147487
Secondary Fire                           137771
False alarm - Malicious                   20515
Flood call attended - Batch mobilised      3044
Chimney Fire                                541
Late Call                                   222
Use of Special Operations Room               60
Name: StopCodeDescription, dtype: int64
=========================
Dwelling             699344
Non Residential      345148
Outdoor              129092
Road Vehicle         111314
Other Residential     90275
Outdoor Structure     86880
Rail Vehicle           1201
Aircraft               1009
Boat                    797
Name: PropertyCategory, dtype: int64
=========================
Purpose Built Flats/Maisonettes - 4 to 9 storeys      174302
House - single occupancy                              162988
Purpose Built Flats/Maisonettes - Up to 3 storeys     132783
Self contained Sheltered Housing                       73817
Car                                                    69911
                                                       ...
Castle (part not open to public)                           3
Greenhouse (commercial) polytunnel                         2
Military helicopter                                        2
Racecourse                                                 1
Silo                                                       1
Name: PropertyType, Length: 291, dtype: int64
=========================
260.0      413985
352.0       97858
326.0       91378
328.0       90810
339.0       90728
            ...
23798.0         1
47922.0         1
17930.0         1
17278.0         1
42224.0         1
Name: Notional Cost (£), Length: 1078, dtype: int64
=========================
1.0      1207591
2.0       187201
3.0        32125
4.0        11462
5.0         6507
          ...
141.0          1
118.0          1
121.0          1
75.0           1
106.0          1
Name: NumCalls, Length: 90, dtype: int64
=========================