In [15]:
import pandas as pd
from sklearn import tree
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [16]:
# define cols to load
part = 100000
desired_cols = ['DateOfCall', 'StopCodeDescription', 'PropertyType', 'FirstPumpArriving_AttendanceTime']

# load dataset, remove NaN
ds = pd.read_csv('data/lfb_incident.csv', usecols=desired_cols)
ds = ds.dropna()
ds = ds[0:part]

In [17]:
ds[0:5]

,DateOfCall,StopCodeDescription,PropertyType,FirstPumpArriving_AttendanceTime
0,01 Jan 2009,Special Service,Car,319.0
2,01 Jan 2009,Secondary Fire,Road surface/pavement,308.0
3,01 Jan 2009,Secondary Fire,Domestic garden (vegetation not equipment),210.0
4,01 Jan 2009,Secondary Fire,Cycle path/public footpath/bridleway,233.0
5,01 Jan 2009,AFA,Purpose Built Flats/Maisonettes - Up to 3 stor...,172.0

In [18]:
ds["DateOfCall"] = ds["DateOfCall"].apply(lambda x: datetime.strptime(x, '%d %b %Y').strftime('%Y-%m-%d'))
for col in ['DateOfCall', 'StopCodeDescription', 'PropertyType']:
    unique_date = ds[col].unique()
    for date in unique_date:
        ds[col] = ds[col].replace(date, np.where(unique_date == date)[0][0])
ds.to_csv('out.csv', index=False)

In [19]:
ds[:50]

,DateOfCall,StopCodeDescription,PropertyType,FirstPumpArriving_AttendanceTime
0,0,0,0,319.0
2,0,1,1,308.0
3,0,1,2,210.0
4,0,1,3,233.0
5,0,2,4,172.0
6,0,0,0,522.0
7,0,1,5,342.0
8,0,1,6,255.0
9,0,2,7,297.0
11,0,0,8,256.0
12,0,1,9,595.0
13,0,0,1,56.0
14,0,2,10,239.0
15,0,0,11,696.0
16,0,3,12,669.0
17,0,0,11,313.0
18,0,4,13,131.0
20,0,0,14,220.0
22,0,3,15,349.0
23,0,4,4,369.0
24,0,2,15,285.0
25,0,3,16,190.0
26,0,3,11,652.0
27,0,2,17,388.0
28,0,0,11,276.0
29,0,3,14,331.0
30,0,0,4,657.0
31,0,1,18,336.0
32,0,1,19,281.0
33,0,3,16,381.0
34,0,4,4,116.0
35,0,4,8,203.0
36,0,2,20,283.0
37,0,1,9,457.0
38,0,2,10,266.0
40,0,3,21,275.0
41,0,0,4,646.0
42,0,0,22,245.0
43,0,0,16,591.0
44,0,4,4,472.0
46,0,0,14,280.0
48,0,0,8,343.0
49,0,3,6,552.0
50,0,2,23,189.0
51,0,0,11,235.0
52,0,0,1,348.0
53,0,0,14,275.0
54,0,0,24,340.0
55,0,0,8,488.0
56,0,0,0,312.0

In [75]:
clf = tree.DecisionTreeClassifier()
clf.fit(X_train, y_train)

DecisionTreeClassifier()